Fix computing of array element type for `∇eachslice`
JuliaDiff/ChainRules.jl pull request #808
Opened 2024-09-16 01:36 UTC by BioTurboNick

Fixes #807

Added test, but I'm not sure it actually exercises the path observed in the above issue.

2024-09-16 12:32 UTC, BioTurboNick commented
Other than the formatter, all the failures seem to be due to the fact that the changes mean Julia currently isn't fully inferring the output anymore. I'll see if there's anything to do about that.

2024-09-16 13:56 UTC, BioTurboNick commented
Switching to `Base.promote_eltype` addresses the inference issue, but that's not a public API in base.

2024-09-16 21:23 UTC, BioTurboNick commented
Huh. I'm not sure why the inference test is failing on 1.6 only. It's inferring `Union{NoTangent, Vector{Float64})` instead of just Vector{Float64}'.

2024-09-17 09:46 UTC, simeonschaub requested changes
I believe the original intent with the design of `similar` was to support cases like `Vector{Vector{Float64}}` where `zero(Vector{Float64})`. That of course doesn't work though since `similar` will just produce `#undef`s here making this fail anyways.

Looks good to me minus the methods that need to be moved to ChainRulesCore. Could you make a PR there (ideally with some unit tests), so we can tag a new version there and then change the compat here.

2024-09-17 09:46 UTC, simeonschaub commented on src/rulesets/Base/indexing.jl
> +Base.eltype(::Type{NoTangent}) = NoTangent
Can you make a PR to ChainRulesCore?

2024-09-17 14:25 UTC, BioTurboNick commented on src/rulesets/Base/indexing.jl
> +Base.eltype(::Type{NoTangent}) = NoTangent
Done!

2024-09-17 22:18 UTC, simeonschaub commented
Just needs to drop the changes already in https://github.com/JuliaDiff/ChainRulesCore.jl/pull/682 and bump the compat for ChainRulesCore

2024-09-18 00:13 UTC, BioTurboNick commented
done and done

2024-09-18 09:01 UTC, simeonschaub commented
Hmm, looks like the format suggestions are not working properly (Maybe because it's on a fork?) If you look at the CI logs, you can see that it complains about the formatting of line 257 in the tests. Once that's fixed this looks good to go!

2024-09-18 09:09 UTC, devmotion commented
> (Maybe because it's on a fork?) 

Yes, due to restricted permissions for forks the suggestions can only be shown in the logs but not as actual suggestions in the PR.

2024-09-18 13:54 UTC, simeonschaub approved these changes

2024-09-18 15:11 UTC, merged